# Default values for ticketing-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ticketing-service
  tag: latest
  pullPolicy: IfNotPresent
  postgres_repository_base: postgres:13.2-alpine

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 2001
  runAsGroup: 2002
  enable : true

service:
  type: NodePort
  port: 8080
  nodePort: 30031

postgres:
  secret_key: password
  crd: EesPostgresAccount
  hook_delete_policy: before-hook-creation
  targetName: eis-common-postgres
  service_host_key : service-host
  service_port_key : service-port
  dbname_key : dbname
  dbuser_key : user
  enabled: true
  mountPath: /etc/postgres
  secretPath: secret/.postgres

reservationdb:
  secret_name: ticketingservice-eespostgresaccount-secret
  namespace: edison-system
  name: ticketingservice
  user: ticketingserviceuser
  configmap: ticketingservice-eespostgresaccount-configmap
  ticketing_service_table: reservation

persistence:
  enabled: true
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  size: 200Mi
  sqliteMountPath: /var/db
  #existingClaim:
  
rmq:
  configmap: ticketingservice-eesrabbitmqaccount-configmap
  secret: ticketingservice-eesrabbitmqaccount-secret
  crd: EesRabbitmqAccount
  namespace: edison-system
  name: ticketingservice
  vhostname: ticketingservicermqhost
  username: ticketingservicermquser
  enabled: true
  mountPath: /etc/rmq
  secretPath: secret/.rabbitmq

env:
  RMQ_RETRY_DELAY_MILLISEC: 50
  RMQ_RETRY_MAX_ATTEMPTS: 3
  RMQ_CONNECTION_TIME_OUT_MS: 50
  DB_CONNECTION_TIMEOUT_SECOND: 1

# Override default liveness & readiness probes
probes:
  liveness:
    initialDelay: 20
    timeoutSeconds: 1
    failureThreshold: 3
    periodSeconds: 60
  readiness:
    initialDelay: 20
    timeoutSeconds: 1
    failureThreshold: 3
    periodSeconds: 60

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /tickets/$1
  labels: {}
  path: /tickets/?(.*)