{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "ticketing-service.fullname" . }}-ingress
  namespace: {{ default "edison-system" .Release.Namespace }}
  labels:
    app: {{ template "ticketing-service.name" . }}
    chart: {{ template "ticketing-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "ticketing-service.fullname" . }}
          servicePort: {{ .Values.service.port }}
{{- end }}