---
{{- if .Values.postgres.enabled }}
apiVersion: ees.ge.com/v1
kind: {{ .Values.postgres.crd }}
metadata:
  name: {{ .Values.reservationdb.name }} 
  namespace: {{ default "edison-system" .Release.Namespace }}  
spec:
    clientid: {{ .Values.reservationdb.name }}
    clientns: {{ default "edison-system" .Release.Namespace }} 
    targetname: {{ .Values.postgres.targetName }}
{{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
    name: {{ .Values.reservationdb.name }}-createtable
spec:
    template:
        metadata:
            name: {{ .Values.reservationdb.name }}-createtable
        spec:
        {{- if .Values.securityContext.enable }}
            securityContext:
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
        {{- end }}
            containers:
            -   name: postgres
                image: {{ .Values.image.postgres_repository_base }}
                env:
                -   name: DB_NAME
                    valueFrom:
                        configMapKeyRef:
                            name: {{ .Values.reservationdb.configmap }}
                            key: {{ .Values.postgres.dbname_key }}
                -   name: POSTGRES_USER
                    value: {{ .Values.reservationdb.user }}
                -   name: PGPASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Values.reservationdb.secret_name }}
                            key: {{ .Values.postgres.secret_key }}
                -   name: DB_PORT
                    valueFrom:
                        configMapKeyRef:
                            name: {{ .Values.reservationdb.configmap }}
                            key:  {{ .Values.postgres.service_port_key }}
                -   name: HOST
                    valueFrom:
                        configMapKeyRef:
                            name: {{ .Values.reservationdb.configmap }}
                            key: {{ .Values.postgres.service_host_key }}
                command: ["bin/bash", "-c",
                                        "psql -h $HOST -p $DB_PORT -U $POSTGRES_USER -d $DB_NAME -c \"CREATE TABLE IF NOT EXISTS {{ .Values.reservationdb.ticketing_service_table }}(ticket_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id VARCHAR (34) NOT NULL,name VARCHAR (120) NOT NULL,place_to VARCHAR (34) NOT NULL,place_from VARCHAR (34) NOT NULL,date VARCHAR (34) NOT NULL,time VARCHAR (34) NOT NULL);\""]
            restartPolicy: Never
    backoffLimit: 5
{{- end }}
---