/*
This class contains ticketing-service constants
*/
package util

const (
	//DB KEY CONSTANTS
	DB_HOST                       = "HOST"
	DB_PORT                       = "DB_PORT"
	DB_USER                       = "DB_USER"
	DB_NAME                       = "DB_NAME"
	TICKETING_SERVICE_DB_PASSWORD = "TICKETING_SERVICE_DB_PASSWORD"
	TICKETING_SYSTEM_DB_TABLE     = "TICKETING_SYSTEM_DB_TABLE"
	TICKETING_SERVICE_PORT        = "TICKETING_SERVICE_PORT"
	IS_POSTGRES_ENABLED           = "IS_POSTGRES_ENABLED"
	DB_CONNECTION_TIMEOUT_SECOND  = "DB_CONNECTION_TIMEOUT_SECOND"
	//SQLITE_MOUNT_PATH             = "SQLITE_MOUNT_PATH"
	CREATE_TABLE_QUERY   = "CREATE_TABLE_QUERY"
	POSTGRES_SECRET_PATH = "POSTGRES_SECRET_PATH"

	//RMQ KEY CONSTANTS
	RMQ_EVENT_EXCHANGE         = "RMQ_EVENT_EXCHANGE"
	RMQ_HOST                   = "RMQ_HOST"
	RMQ_PORT                   = "RMQ_PORT"
	RMQ_USER                   = "RMQ_USER"
	RMQ_PASSWORD               = "RMQ_PASSWORD"
	RMQ_RETRY_MAX_ATTEMPTS     = "RMQ_RETRY_MAX_ATTEMPTS"
	RMQ_VHOST                  = "RMQ_VHOST"
	RMQ_RETRY_DELAY_MILLISEC   = "RMQ_RETRY_DELAY_MILLISEC"
	RMQ_CONNECTION_TIME_OUT_MS = "RMQ_CONNECTION_TIME_OUT_MS"
	IS_RMQ_ENABLED             = "IS_RMQ_ENABLED"
	RMQ_SECRET_PATH            = "RMQ_SECRET_PATH"

	//log level
	LOG_LEVEL = "LOG_LEVEL"

	//Error codes thrown by postgres
	PG_PRIMARYKEY_CONSTRAINT_ERR_CODE = "23505"

	DB_PING_TIMEOUT = 500

	// Database drivers
	POSTGRES_DRIVER = "postgres"
)
